---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '512'
        cpus: '2'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.100
            forwarded_port:
                RdEhw3kDRujd:
                    host: '6242'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            HvZ0waPJas5Q:
                source: ./
                target: /var/www
                # nfs | rsync
                sync_type: nfs
                rsync:
                    args:
                        # uncomment next line for set custom chmod
                        #- '--chmod=ug=rwX,o=rxX'
                        - '--verbose'
                        - '--archive'
                        - '--delete'
                        - '-z'
                    exclude:
                        - .vagrant/
                        # add your excluded folders here
                        - 'tmp/'
                        - 'nbproject/'
                        - '_webfiles/cache/*/'
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - build-essential
        - libmagickwand-dev
        - curl
        - git-core
        - php-console-table
        - htop
        - vim
        - ccze
        - multitail
        - ghostscript
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
        - expires
        - headers
        - mime_magic
        - ssl
        - deflate
    vhosts:
        raIyA4vMacMr:
            servername: dev.comexpertise.com
            docroot: /var/www/_webfiles
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        ethxCEPA8iSO:
            server_name: dev.comexpertise.com
            www_root: /var/www/_webfiles
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - imap
            - mbstring
            - tidy
            - xmlrpc
            - common
            - cgi
            - sqlite
            - recode
        pear: {  }
        pecl:
            - pecl_http
            - pdflib
            - uploadprogress
            - imagick
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        max_execution_time: '600'
        memory_limit: 256M
        upload_max_filesize: 20M
        post_max_size: 25M
        max_input_time: '300'
        max_input_vars: '2000'
    timezone: Europe/Paris
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: '1'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        YzRHcJaoHMI0:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        FWB3Vc2LyWHr:
            version: ''
mysql:
    install: '1'
    root_password: rootpassword
    adminer: 0
    databases:
        yaNoPhIUHbOl:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: dbpassword
            sql_file: /var/www/_sql/dbname.sql
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: headers
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true

